// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdfMasterIndex.Service.Infrastructure.Persistence;
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.

#nullable disable

namespace PdfMasterIndex.Service.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MasterIndexDbContext))]
    [Migration("20260409111551_add tags to scan paths")]
    partial class addtagstoscanpaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ScanPathId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScanPathId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DocumentPosition")
                        .HasColumnType("bigint");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<long>("PagePosition")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WordId");

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.ScanPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("ScanPaths");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ignored")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("ScanPathTag", b =>
                {
                    b.Property<Guid>("ScanPathsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScanPathsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ScanPathTag");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Document", b =>
                {
                    b.HasOne("PdfMasterIndex.Service.Domain.Index.ScanPath", "ScanPath")
                        .WithMany("Documents")
                        .HasForeignKey("ScanPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanPath");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Occurrence", b =>
                {
                    b.HasOne("PdfMasterIndex.Service.Domain.Index.Document", "Document")
                        .WithMany("Content")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PdfMasterIndex.Service.Domain.Index.Word", "Word")
                        .WithMany("Occurrences")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("ScanPathTag", b =>
                {
                    b.HasOne("PdfMasterIndex.Service.Domain.Index.ScanPath", null)
                        .WithMany()
                        .HasForeignKey("ScanPathsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PdfMasterIndex.Service.Domain.Index.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Document", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.ScanPath", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Domain.Index.Word", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
