// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdfMasterIndex.Service.Infrastructure.Persistence;

#nullable disable

namespace PdfMasterIndex.Service.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MasterIndexDbContext))]
    partial class MasterIndexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ScanPathId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScanPathId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Occurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DocumentPosition")
                        .HasColumnType("bigint");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<long>("PagePosition")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WordId");

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.ScanPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("ScanPaths");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ignored")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Document", b =>
                {
                    b.HasOne("PdfMasterIndex.Service.Infrastructure.Persistence.Models.ScanPath", "ScanPath")
                        .WithMany("Documents")
                        .HasForeignKey("ScanPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanPath");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Occurrence", b =>
                {
                    b.HasOne("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Document", "Document")
                        .WithMany("Content")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Word", "Word")
                        .WithMany("Occurrences")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Document", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.ScanPath", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PdfMasterIndex.Service.Infrastructure.Persistence.Models.Word", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
